baseURL = 'https://red-light-therapy.theqoder.com/'
languageCode = "en-us"
title = "Infrared Therapy Lamp | Your Path to Recovery"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
[params]
  author = "Josue Pacheco"
[modules]
  disable = true
[sitemap]
  changefreq = "weekly"
  priority = 0.5