baseURL = 'http://localhost:1313/'
languageCode = "en-us"
title = "Infrared Therapy Lamp | Your Path to Recovery"
theme = ""
disableKinds = ["taxonomy"]
enableGitInfo = true
[params]
  author = "Josue Pacheco"
