baseURL = 'http://localhost:1313/'
languageCode = "en-us"
title = "Infrared Therapy Lamp | Your Path to Recovery"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
[params]
  author = "Josue Pacheco"
[modules]
  disable = true
